config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

   root 'order#new'
   post 'create_order' => 'order#create' , :as=>'create_order'
   get 'receipt'=> 'order#receipt' , :as=>'receipt'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  belongs_to :state

  def self.sales_tax_amount(product_id, state_id, quantity)
    product=Product.find(product_id)
    tax=TaxRate.where(:category_id => product.category_id, :state_id => state_id ).first.amount
    sales_tax= ((quantity.to_i*product.price)/100)*tax
    sales_tax1=self.rounded_tax(sales_tax)
    if sales_tax1.nil?
      return sales_tax
    else
      return sales_tax1
    end
  end

  def self.total_price(product_id , quantity )
    price=Product.find(product_id).price
    price*quantity.to_i
  end

  def self.rounded_tax(sales_tax)
    fraction1=sales_tax.modulo(1).round(2)
    fraction=fraction1.modulo(0.1).round(2)
    if fraction <= 0.05 && fraction != 0.00
     s_tax=sales_tax+(0.05-fraction)
    elsif   fraction > 0.05 && fraction != 0.00
      s_tax=sales_tax+(0.10 - fraction)
    end
    return s_tax
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/tax_rate.rb
class TaxRate < ActiveRecord::Base
  belongs_to :state
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/order_controller.rb
class OrderController < ApplicationController

  def new
   @order = Order.new
  end

  def create

    sales_tax=Order.sales_tax_amount(order_params[:product_id], order_params[:state_id], order_params[:quantity])
    total_price=Order.total_price(order_params[:product_id], order_params[:quantity] )
    @order = Order.new
    @order.state_id=order_params[:state_id]
    @order.product_id=order_params[:product_id]
    @order.quantity=order_params[:quantity]
    @order.sales_tax=sales_tax
    @order.total=total_price
    @order.save
    render :receipt
  end

  def receipt

  end

  def order_params
    params.require(:order).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Receipt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/order/new.html.erb
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container">
  <div class="row">
    <div class="col-md-offset-5 col-md-3">
      <div class="form-login">
        <a href="/admin">Admin</a>
        <h4>Welcome back.</h4>
        <%= simple_form_for @order, url: create_order_url, as: 'order'  do |f| %>

            <%= f.input :product_id do %>
                <%= f.select :product_id, Product.all.map { |r| [r.name, r.id ] }, include_blank: false, :class=>"form-control input-sm chat-input" %>
            <% end %>

            <%= f.input :quantity, placeholder: 'quantity', :class=>"form-control input-sm chat-input" %>

            <%= f.input :state_id do %>
                <%= f.select :state_id, State.all.map { |r| [r.name, r.id ] }, include_blank: false, :class=>"form-control input-sm chat-input" %>
            <% end %>



            <%= f.button :submit, :class=>"btn btn-primary btn-md" %>
        <% end %>

        <
      </div>

    </div>
  </div>
</div>

app/views/order/receipt.html.erb
<div class="container" style="margin-top: 20px ">
  <div class="row">
    <div class="well col-xs-10 col-sm-10 col-md-6 col-xs-offset-1 col-sm-offset-1 col-md-offset-3">
      <div class="row" style="margin-left: 37px;">
        <div class="col-xs-6 col-sm-6 col-md-6">
          <address>
            <strong>Amitkumar Wagh</strong>
            <br>
            Pune
            <br>
            Maharashtra
            <br>
            <abbr title="Phone">P:</abbr> 9130058177
          </address>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 text-right">
          <p>
            <em>Date: <%= @order.created_at %></em>
          </p>
          <p>
            <em>Receipt #: <%= @order.id %></em>
          </p>
        </div>
      </div>
      <div class="row" style="margin-left: 37px;">
        <div class="text-center">
          <h1>Receipt</h1>
        </div>
        </span>
        <table class="table table-hover">
          <thead>
          <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th class="text-center">Price</th>
            <th class="text-center">Total</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td class="col-md-9"><h4><em><%= @order.product.name %></em></h4></td>
            <td class="col-md-1" > <%= @order.quantity %></td>
            <td class="col-md-1 text-center">$<%= @order.product.price %></td>
            <td class="col-md-1 text-center">$<%= @order.total%></td>
          </tr>

          <tr>
            <td>   </td>
            <td>   </td>
            <td class="text-right">
              <p>
                <strong>Subtotal: </strong>
              </p>
              <p>
                <strong>Tax: </strong>
              </p></td>
            <td class="text-center">
              <p>
                <strong>$<%= @order.total%></strong>
              </p>
              <p>
                <strong>$<%= @order.sales_tax%></strong>
              </p></td>
          </tr>
          <tr>
            <td>   </td>
            <td>   </td>
            <td class="text-right"><h4><strong>Total: </strong></h4></td>
            <td class="text-center text-danger"><h4><strong>$<%= @order.total + @order.sales_tax%></strong></h4></td>
          </tr>
          </tbody>
        </table>
        <button type="button" class="btn btn-success">
          Pay Now   <span class="glyphicon glyphicon-chevron-right"></span>
        </button></td>
      </div>
    </div>
  </div>
    </div>